# Generated by Django 2.1.7 on 2019-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='имя категория')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='имя категория')),
            ],
        ),
    ]
